name: nightly-build

on:
  schedule:
  - cron: '0 3 * * *'  # 12 AM EST
  push:  


env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

      # Checkout Step
      - name: Clone Repository
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Checkout Failure
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@master
        with:
          args: gh run view --job checkout --log

      # Python Setup Step
      - name: Setup Python
        id: python-setup
        uses: actions/setup-python@v4
        with:
          python-version: '4.9'
      - name: Python Setup Failure
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@master
        with:
          args: f'Python step failed!. ${{join(steps.python-setup.outputs.*, '\n')}}'

      - name: Install Python Dependencies
        run: pip3 install -r requirements.txt
      - name: Format Python Code
        run: black --verbose --exclude=docker-stacks .
      - name: Build Containers
        run: make gpu-build
      - name: Tag Containers
        run: make tag-all
      - name: Execute Docker-Stacks Tests
        run: python tests/exec_docker_stacks_tests.py
      - name: Test For Cuda
        run: pytest -x tests/cuda_test.py
      - name: Log Into Container Registry
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push To Container Registry
        run: make push-all
      - name: Notify Channels
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build and push complete!'
